# See: https://gohugo.io/getting-started/configuration/

####################
# Site information #
####################
baseURL: https://wonyoungjang.org/hugo-PolyRhythmic-demo
copyright: |
  <!--Creative Commons License-->
    This site is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/).
  <!--/Creative Commons License-->
languageCode: en-US
theme: ["PolyRhythmic"]
title: PolyRhythmic
# timeZone: (string)

###############
# Directories #
###############
# archetypeDir: archetypes
# assetDir: assets
# contentDir: content
# dataDir: data
# publishDir: public
# themesDir: themes

######################
# Content management #
######################
# defaultContentLanguage: en
# defaultContentLanguageInSubdir: false
# disableKinds:
# - taxonomy
# - term
# enableEmoji: false
enableGitInfo: true
# enableMissingTranslationPlaceholders: false
# hasCJKLanguage: false
# newContentEditor: (string)
# noChmod: false
# noTimes: false
# pluralizeListTitles: true
# summaryLength: 70
# capitalizeListTitles: true
# titleCaseStyle: ap

##################
# Build settings #
##################
# buildDrafts: false
# buildExpired: false
# buildFuture: false
cleanDestinationDir: true
# disableHugoGeneratorInject: false

##################
# URL management #
##################
# canonifyURLs: false
# disableAliases: false
# disablePathToLower: false
# relativeURLs: false
# removePathAccents: false
# uglyURLs: false
# refLinksErrorLevel: ERROR
# refLinksNotFoundURL: (string)

######################
# Markup & rendering #
######################
# renderSegments: (string slice)

########################
# Deployment & hosting #
########################
enableRobotsTXT: true

########################
# Server & development #
########################
# disableLiveReload: false
# timeout: 30s
# watch: false

###################
# Keyed settings  #
###################
# (build.yaml)
# (caches.yaml)
# (cascade.yaml)
# (deployment.yaml)
# (disableLanguages.yaml)
# (frontmatter.yaml)
# (httpcache.yaml)
# (imaging.yaml)
# (languages.yaml)
# (markup.yaml)
# (mediatypes.yaml)
# (menus.yaml)
# (minify.yaml)
# (module.yaml)
# (outputFormats.yaml)
# (outputs.yaml)
# (pagination.yaml)
# (params.yaml)
# (permalinks.yaml)
# (privacy.yaml)
# (related.yaml)
# (security.yaml)
# (segments.yaml)
# (server.yaml)
# (services.yaml)
# (sitemap.yaml)
# (taxonomies.yaml)
