dateFormat: January 2, 2006
debug: false
description: "Demo site for PolyRhythmic theme"

assets:
  favicon: sitelogo.svg

home:
  title: PolyRhythmic Demo
  tagline: A fast, lightweight Material Design 3 Hugo theme

  welcome: Welcome to the demo page of the PolyRhythmic Hugo theme
  blurb: |
    PolyRhythmic is based on Material Design 3

    PolyRhythmic extends the official Material guidelines, while minimizing the amount of scripting

    Show your support: give this a star on GitHub, share, and most importantly, use this theme for you own websites!

  buttons:
    resources:
      - name: Material Design 3 Components
        url: /hugo-PolyRhythmic-demo/components
        icon: settings
      - name: Material Design 3 Layouts
        url: /hugo-PolyRhythmic-demo/layouts
        icon: view_quilt
      - name: Material Design 3 Tokens
        url: /hugo-PolyRhythmic-demo/tokens
        icon: token

author:
  name: Wonyoung Jang
  email: contact@wonyoungjang.org

fuseOpts:
  isCaseSensitive: false
  includeScore: true
  includeMatches: true
  minMatchCharLength: 1
  shouldSort: true
  findAllMatches: false
  keys: ["title", "permalink", "description", "summary", "content"]

  location: 0
  threshold: 0.6
  distance: 100
  ignoreLocation: false

  limit: 12