author:
  name: Wonyoung Jang
  email: contact@wonyoungjang.org

assets:
  favicon: sitelogo.svg

dateFormat: January 2, 2006
debug: false
description: "Demo site for PolyRhythmic theme"

fuseOpts:
  isCaseSensitive: false
  includeScore: true
  includeMatches: true
  minMatchCharLength: 1
  shouldSort: true
  findAllMatches: false
  keys: ["title", "section", "permalink", "description", "summary", "content"]
  location: 0
  threshold: 0.6
  distance: 100
  ignoreLocation: false
  limit: 12

home:
  title: PolyRhythmic Demo
  tagline: A fast, lightweight Material Design 3 Hugo theme

  welcome: Welcome to the demo site for Hugo PolyRhythmic
  blurb: |
    [PolyRhythmic](https://github.com/wonyoung-jang/hugo-PolyRhythmic) is based on Material Design 3

    PolyRhythmic extends the official Material guidelines, while minimizing the amount of scripting

    Show your support: give the theme a [star on GitHub](https://github.com/wonyoung-jang/hugo-PolyRhythmic), share, and most importantly, use it for your own websites!

  buttons:
    material:
      - name: Material Design 3 Components
        url: /hugo-PolyRhythmic-demo/components
        icon: settings
      - name: Material Design 3 Layouts
        url: /hugo-PolyRhythmic-demo/layouts
        icon: view_quilt
      - name: Material Design 3 Tokens
        url: /hugo-PolyRhythmic-demo/tokens
        icon: token
    resources:
      - name: PolyRhythmic Shortcodes
        url: /hugo-PolyRhythmic-demo/polyrhythmic-shortcodes
        icon: code
      - name: Playground
        url: /hugo-PolyRhythmic-demo/playground
        icon: markdown
      - name: View the source for this website
        url: https://github.com/wonyoung-jang/hugo-PolyRhythmic-demo
        icon: frame_source
