author:
  name: Wonyoung Jang
  email: contact@wonyoungjang.org

assets:
  favicon: sitelogo.svg

dateFormat: January 2, 2006
debug: false
description: "Demo site for PolyRhythmic theme"

fuseOpts:
  isCaseSensitive: false
  includeScore: true
  includeMatches: true
  minMatchCharLength: 1
  shouldSort: true
  findAllMatches: false
  keys: ["title", "section", "permalink", "description", "summary", "content"]
  location: 0
  threshold: 0.6
  distance: 100
  ignoreLocation: false
  limit: 12

home:
  title: PolyRhythmic Demo
  tagline: A fast, lightweight Material Design 3 Hugo theme

  welcome: Welcome to the demo site for Hugo PolyRhythmic
  blurb: |
    [PolyRhythmic](https://themes.gohugo.io/themes/hugo-polyrhythmic/) is based on Material Design 3

    PolyRhythmic extends the [official Material guidelines](https://m3.material.io/), while minimizing the amount of scripting

    Show your support: give the theme a [star on GitHub](https://github.com/wonyoung-jang/hugo-PolyRhythmic), share, and most importantly, use it for your own websites!

  buttons:
    material 3:
      - name: Components
        url: /components
        icon: settings
      - name: Layouts
        url: /layouts
        icon: view_quilt
      - name: Tokens
        url: /tokens
        icon: token
    resources:
      - name: About
        url: /about
        icon: info
      - name: Contact
        url: /contact
        icon: contact_page
      - name: Keyboard shortcuts
        url: /keyboard-shortcuts
        icon: keyboard
      - name: PolyRhythmic Shortcodes
        url: /polyrhythmic-shortcodes
        icon: code
      - name: Playground
        url: /playground
        icon: markdown
      - name: View the source for this website
        url: https://github.com/wonyoung-jang/hugo-PolyRhythmic-demo
        icon: frame_source
    hugo:
      - name: Default Content Archetype
        url: /default-content-archetype
        icon: file_copy
      - name: Leaf (no branch)
        url: /leaf-page
        icon: eco
      - name: Branch
        url: /branch
        icon: spa
      - name: Branch → Leaf
        url: /branch/leaf
        icon: potted_plant
      - name: Example taxonomy
        url: /example_taxonomies/
        icon: atr
      - name: Example term
        url: /example_taxonomies/example_term/
        icon: label
      - name: Page with example taxonomy
        url: /page-with-example_taxonomy/
        icon: description
